FROM node:20.5.0-alpine3.18
#Workdir es declarar el espacio de trabajo
WORKDIR /app/
#Copy lo que hara es copiar la carpeta de actual (.) al directorio app del contenedor (app es el destino)
COPY . .
RUN npm install

